name: crypto_blake
description: Dart bindings for Blake3 hashing algorithm
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  ffi: ^2.0.1
  path: ^1.8.2
  typed_data: ^1.3.1

dev_dependencies:
  ffigen: ^7.2.4
  test: ^1.22.0

ffigen:
  name: 'Blake3'
  output: 'lib/bindings/blake3.dart'
  headers:
    entry-points:
      - 'blake3_library/blake3.h'
